# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7ee448ca2272ba9cb6ea7f92f9658e04620c37e38734b9294171f68af4994bbecc90359c6163da330d9a25b8f1800537a4f4012ffd0f1e24bf9c34d24fb7d37

test:
  secret_key_base: ff70701bfadf4eb4f89505e37ec714353145c649035dbe8a9822e9cbf42480d719ad432cea7da2bf31f49dbf7c98c79aa4611ef62e8ba30354f6bbb3fc22e484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
